name: Build and Upload

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v1

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
        env:
          # CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
