name: Build and Upload

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Package and release for Retail
        uses: BigWigsMods/packager@v1

      - name: Package and release for Classic
        uses: BigWigsMods/packager@v1
        with:
          args: -g classic
      
      - name: Package and release for Burning Crusade
        uses: BigWigsMods/packager@v1
        with:
          args: -g bcc
